# Generated by Django 5.1.7 on 2025-03-13 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlFertilizantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ICA', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.IntegerField()),
                ('valor', models.FloatField()),
                ('fecha_ultima_aplicacion', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlHongos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ICA', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.IntegerField()),
                ('valor', models.FloatField()),
                ('periodo_carencia', models.IntegerField()),
                ('nombre_hongo', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlPlagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ICA', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('frecuencia_aplicacion', models.IntegerField()),
                ('valor', models.FloatField()),
                ('periodo_carencia', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='LaborProductoControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.labor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.controlplagas')),
            ],
        ),
        migrations.AddField(
            model_name='labor',
            name='productos',
            field=models.ManyToManyField(through='gestion.LaborProductoControl', to='gestion.controlplagas'),
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_catastro', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=100)),
                ('productor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fincas', to='gestion.productor')),
            ],
        ),
        migrations.CreateModel(
            name='Vivero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo_cultivo', models.CharField(max_length=100)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viveros', to='gestion.finca')),
            ],
        ),
        migrations.AddField(
            model_name='labor',
            name='vivero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labores', to='gestion.vivero'),
        ),
    ]
